<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer/autoload_real.php';
require_once __DIR__ . '/../mysql.php';

// $archivo = file_get_contents( __DIR__ . '/../mysql.php', FALSE, NULL, 153, 300);
// preg_match_all("/DB_(.*)/", $archivo, $const);
// $array[] = parse_ini_string($const[1][0]);
// $array[] = parse_ini_string($const[1][1]);
// $array[] = parse_ini_string($const[1][2]);

// $name = $array[0]['NAME'];
// $user = $array[1]['USER'];
// $pass = $array[2]['PSW'];
$name = DataBase::DB_NAME;
$host = DataBase::DB_HOST;
$user = DataBase::DB_USER;
$pass = DataBase::DB_PSW;
$port = DataBase::DB_PORT;

try {
    $db_auth = new \PDO("mysql:dbname=$name;host=$host;port=$port;charset=utf8mb4", $user, "$pass");
    return ComposerAutoloaderInitd94e90ad202a875aa033a059b8035a5c::getLoader();
} catch (\Throwable $th) {
    echo "<pre>{$th->getMessage()}</pre>";
    exit;
}
