INSERT INTO clasificaciones_grupos (id_grupo,descripcion,situacion) VALUES 
(1,'ANTIINFECCIOSOS SISTEMICOS',1)
,(2,'ANTIPARASITARIOS',1)
,(3,'APARATO CARDIOVASCULAR',1)
,(4,'APARATO DIGESTIVO',1)
,(5,'APARATO GENITOURINARIO',1)
,(6,'APARATO LOCOMOTOR',1)
,(7,'APARATO RESPIRATORIO',1)
,(8,'DROGAS ONCOLOGICAS E INMUNOSUPRESORES',1)
,(9,'GERIATRICOS',1)
,(10,'HORMONAS NATURALES Y SINTETICAS',1)
;
INSERT INTO clasificaciones_grupos (id_grupo,descripcion,situacion) VALUES 
(11,'INMUNIZACION PASIVA Y ACTIVA',1)
,(12,'MODIFICADORES DEL METABOLISMO',1)
,(13,'ODONTOLOGICOS',1)
,(14,'OFTALMOLOGICOS',1)
,(15,'OTORRINOLARINGOLOGIA',1)
,(16,'PIEL Y MUCOSAS',1)
,(17,'PRUEBAS DIAGNOSTICAS',1)
,(18,'SANGRE, LIQUIDOS Y ELECTROLITOS',1)
,(19,'SISTEMA  NERVIOSO',1)
,(20,'TOXICOS',1)
;
INSERT INTO clasificaciones_grupos (id_grupo,descripcion,situacion) VALUES 
(21,'VITAMINAS NUTRIENTES',1)
,(22,'NINGUNO',1)
;